# -*- coding: utf-8 -*-
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox  

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint)  
        MainWindow.resize(788, 306)
        MainWindow.setFixedSize(788, 306)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(140, 40, 71, 20))
        self.lineEdit_1.setObjectName("textEdit")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(70, 5, 721, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 30, 16, 81))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(220, 40, 54, 12))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(220, 40, 41, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 121, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 70, 71, 20))
        self.lineEdit_2.setObjectName("textEdit_2")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(220, 70, 41, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(280, 40, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 40, 71, 20))
        self.lineEdit_3.setObjectName("textEdit_3")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(450, 40, 41, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(280, 70, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 70, 71, 20))
        self.lineEdit_4.setObjectName("textEdit_4")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(450, 70, 111, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(570, 40, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(660, 40, 71, 20))
        self.lineEdit_5.setObjectName("textEdit_5")
        self.label_12 = QtWidgets.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(740, 40, 21, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(570, 70, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(660, 70, 71, 20))
        self.lineEdit_6.setObjectName("textEdit_6")
        self.label_14 = QtWidgets.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(740, 70, 41, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(17, 100, 771, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(780, 20, 16, 91))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_15 = QtWidgets.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(10, 120, 54, 12))
        self.label_15.setObjectName("label_15")
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setGeometry(QtCore.QRect(70, 110, 721, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setGeometry(QtCore.QRect(10, 140, 16, 191))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_16 = QtWidgets.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(40, 150, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(140, 150, 91, 16))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralWidget)
        self.label_18.setGeometry(QtCore.QRect(240, 150, 41, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralWidget)
        self.label_19.setGeometry(QtCore.QRect(40, 180, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralWidget)
        self.label_20.setGeometry(QtCore.QRect(140, 180, 91, 16))
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralWidget)
        self.label_21.setGeometry(QtCore.QRect(240, 180, 41, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralWidget)
        self.label_22.setGeometry(QtCore.QRect(40, 210, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralWidget)
        self.label_23.setGeometry(QtCore.QRect(140, 210, 91, 16))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralWidget)
        self.label_24.setGeometry(QtCore.QRect(240, 210, 41, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralWidget)
        self.label_25.setGeometry(QtCore.QRect(20, 240, 111, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralWidget)
        self.label_26.setGeometry(QtCore.QRect(140, 240, 91, 16))
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralWidget)
        self.label_27.setGeometry(QtCore.QRect(240, 240, 41, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralWidget)
        self.label_28.setGeometry(QtCore.QRect(40, 270, 91, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralWidget)
        self.label_29.setGeometry(QtCore.QRect(140, 270, 91, 16))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralWidget)
        self.label_30.setGeometry(QtCore.QRect(240, 270, 41, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralWidget)
        self.label_31.setGeometry(QtCore.QRect(400, 150, 101, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralWidget)
        self.label_32.setGeometry(QtCore.QRect(520, 150, 91, 16))
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralWidget)
        self.label_33.setGeometry(QtCore.QRect(620, 150, 51, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralWidget)
        self.label_34.setGeometry(QtCore.QRect(370, 180, 131, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralWidget)
        self.label_35.setGeometry(QtCore.QRect(520, 180, 91, 16))
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralWidget)
        self.label_36.setGeometry(QtCore.QRect(620, 180, 51, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralWidget)
        self.label_37.setGeometry(QtCore.QRect(410, 210, 101, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralWidget)
        self.label_38.setGeometry(QtCore.QRect(520, 210, 91, 16))
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.centralWidget)
        self.label_39.setGeometry(QtCore.QRect(620, 210, 71, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralWidget)
        self.label_40.setGeometry(QtCore.QRect(380, 240, 121, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralWidget)
        self.label_41.setGeometry(QtCore.QRect(520, 240, 91, 16))
        self.label_41.setText("")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.centralWidget)
        self.label_42.setGeometry(QtCore.QRect(620, 240, 71, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.line_7 = QtWidgets.QFrame(self.centralWidget)
        self.line_7.setGeometry(QtCore.QRect(20, 290, 771, 31))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralWidget)
        self.line_8.setGeometry(QtCore.QRect(780, 120, 16, 181))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.get_text) 
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "辣椒酱物料衡算"))
        self.label.setText(_translate("MainWindow", "已知参数"))
        self.label_2.setText(_translate("MainWindow", "辣椒酱年产量："))
        self.label_4.setText(_translate("MainWindow", "吨/年"))
        self.label_5.setText(_translate("MainWindow", "      日工作时间："))
        self.label_6.setText(_translate("MainWindow", "小时"))
        self.label_7.setText(_translate("MainWindow", "罐装平容量："))
        self.label_8.setText(_translate("MainWindow", "ML"))
        self.label_9.setText(_translate("MainWindow", "产品合格率："))
        self.label_10.setText(_translate("MainWindow", "(0-1之间取值)"))
        self.label_11.setText(_translate("MainWindow", "年工作时间："))
        self.label_12.setText(_translate("MainWindow", "天"))
        self.label_13.setText(_translate("MainWindow", "       箱容量："))
        self.label_14.setText(_translate("MainWindow", "瓶/箱"))
        self.label_15.setText(_translate("MainWindow", "计算参数"))
        self.label_16.setText(_translate("MainWindow", "实际年产量："))
        self.label_18.setText(_translate("MainWindow", "吨/年"))
        self.label_19.setText(_translate("MainWindow", "平均日产量："))
        self.label_21.setText(_translate("MainWindow", "吨/日"))
        self.label_22.setText(_translate("MainWindow", "    日产瓶数："))
        self.label_24.setText(_translate("MainWindow", "瓶/日"))
        self.label_25.setText(_translate("MainWindow", " 每小时产瓶数："))
        self.label_27.setText(_translate("MainWindow", "瓶/时"))
        self.label_28.setText(_translate("MainWindow", "    日产箱数："))
        self.label_30.setText(_translate("MainWindow", "箱/日"))
        self.label_31.setText(_translate("MainWindow", "每分钟产瓶数："))
        self.label_33.setText(_translate("MainWindow", "瓶/min"))
        self.label_34.setText(_translate("MainWindow", "每分钟实际产瓶数："))
        self.label_36.setText(_translate("MainWindow", "瓶/min"))
        self.label_37.setText(_translate("MainWindow", " 每班日产量："))
        self.label_39.setText(_translate("MainWindow", "箱(班·日)"))
        self.label_40.setText(_translate("MainWindow", " 每班实际日产量："))
        self.label_42.setText(_translate("MainWindow", "吨(班·日)"))
        self.pushButton.setText(_translate("MainWindow", "开始计算"))
        self.pushButton_2.setText(_translate("MainWindow", "退出程序"))
    def get_text(self): 
        self.arg_1=self.lineEdit_1.text()  #年产量
        self.arg_2=self.lineEdit_2.text()  #日工作时间
        self.arg_3=self.lineEdit_3.text()  #罐装瓶容量
        self.arg_4=self.lineEdit_4.text()  #产品合格率
        self.arg_5=self.lineEdit_5.text()  #年工作天数
        self.arg_6=self.lineEdit_6.text()  #箱容量
        try:
            
            int(self.arg_1)+int(self.arg_2)+int(self.arg_3)+float(self.arg_4)+int(self.arg_5)+int(self.arg_6)
            
            if int(self.arg_1) <= 0:
                myshow=MyWindow().show()
            if int(self.arg_2) <= 0 or int(self.arg_2) > 12:
                myshow=MyWindow().show()
            if float(self.arg_4) >  1 or float(self.arg_4) < 0:
                myshow=MyWindow().show()
            if int(self.arg_5) > 365:
                myshow=MyWindow().show()
            if int(self.arg_6) <= 0:
                myshow=MyWindow().show()
            self.calculate_data()
        except Exception as msg:
            print('请输入正确的数据:'+str(msg))
            myshow=MyWindow()  
            myshow.show()
    def calculate_data(self):
        self.out_arg_1=int(self.arg_1)/float(self.arg_4)  #实际年产量
        self.out_arg_2=self.out_arg_1/int(self.arg_5)  #平均日产量
        self.out_arg_3=(self.out_arg_2 * 1000000)/int(self.arg_3)  #日产瓶数
        self.out_arg_4=self.out_arg_3/int(self.arg_2)  #每小时生产瓶数
        self.out_arg_5=self.out_arg_3/int(self.arg_6)  #日产箱数
        self.out_arg_6=self.out_arg_4/60  #每分钟产瓶数
        self.out_arg_7=self.out_arg_6/0.98  #每分钟实际产瓶数
        self.out_arg_8=self.out_arg_7*int(self.arg_2)*60/int(self.arg_6)  #每班日产量
        self.out_arg_9=self.out_arg_8*int(self.arg_3)*int(self.arg_6)*0.000001  #每班实际日产量
        
        self.label_17.setText('%.5f' % self.out_arg_1)
        self.label_20.setText('%.5f' % self.out_arg_2)
        self.label_23.setText('%.5f' % self.out_arg_3)
        self.label_26.setText('%.5f' % self.out_arg_4)
        self.label_29.setText('%.5f' % self.out_arg_5)
        self.label_32.setText('%.5f' % self.out_arg_6)
        self.label_35.setText('%.5f' % self.out_arg_7)
        self.label_38.setText('%.5f' % self.out_arg_8)
        self.label_41.setText('%.5f' % self.out_arg_9)
        

class MyWindow(QtWidgets.QWidget):  
    def __init__(self,parent=None):
        super().__init__()  
        self.input_error()
    def input_error(self):
        reply = QMessageBox.warning(self,"Error",  "请输入正确的数据,并按照指定的数字范围输入",  QMessageBox.Yes)
        print(reply)
   
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

